language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --no-interaction
  
  # Script, failures in this section will result in build status 'failed'
script: "phpunit -c tests/phpunit.xml"
  
